keys:
  - &users:
    - &willg age10c02spktse006k0jgucc7refhe6jl4s8n9ukjqazv7mw6mdc6yas93cjjg
  - &hosts
    - &andromeda age19h7rnvk8fdznlz66wcv6lpka4tjramsmsuwhsfs0a4fj3u2epd5q76gurj
creation_rules:
  - path_regex: secrets\/secrets\.yaml$
    key_groups:
      - age:
        - *willg
        - *andromeda
  - path_regex: secrets\/willg\.yaml$
    key_groups:
      - age:
        - *willg
  - path_regex: secrets\/andromeda-protonvpn\.conf$
    key_groups:
      - age:
        - *andromeda